pipeline:
  name: Build hello-world
  identifier: Build_hello_world_1674194362386
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: GitClone
                  name: Git Clone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: Master_connector
                    repoName: hello-world
                    build:
                      type: branch
                      spec:
                        branch: main
              - step:
                  type: Run
                  name: Run the file
                  identifier: run_the_file
                  spec:
                    shell: Sh
                    command: |
                      chmod +x demo.sh
                      ./demo.sh
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo "Welcome to Harness CI"
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: sahilnewar/hello-world
        build: <+input>
